@startuml

start

repeat



  :Ввести данные видеозаписи на форме загрузки;
  if (Локальный файл?) then (true)
    
  else (false)
    if (Локальный URL?) then (true)
      : Получить расположение файла\n из БД;
    else (false)
      : Выполнить загрузку видео\nсо стороннего ресурса;
    endif
  endif
  
  :Загрузить видеофайл в хранилище;
  
repeat while (видео загружено либо\nоперация прервана?) is (нет) not (да)

if (Видео загружено?) then (true)
  : Отобразить окно просмотра видео;
else (false)
  : Отобразить главное окно;
endif

stop

@enduml
