@startuml

start

: Выбор плейлиста;

: Поиск видео;

: Выбор видео для добавления;

repeat

  if  (Необходим повторный поиск?) then (true)
  
    : Поиск видео;

    : Выбор видео для добавления;
    
  else (false)
  
  endif;
  
  if (Видео существует и\nне содержится в плейлисте?) then (true)
    
    : Добавить видео в плейлист;
    
  else (false)
  
  endif
  
repeat while (видео добавлено либо\nоперация прервана?) is (нет) not (да)

  : Отобразить окно просмотра плейлиста;

stop

@enduml
